### ISSUE TITLE
how to connect confluence via https (SSL)

### ISSUE THREAD

**Issue by xwyangjshb** [codelibs/curl4j#5]
use plugin Data-Source-confluence to connect confluence workspace, 

{"@timestamp":"2024-01-21T08:52:20.212Z","log.level":"ERROR","message":"Failed to process a data crawling: CONF-8090", "ecs.version": "1.2.0","service.name":"fess","event.dataset":"crawler","process.thread.name":"RMg1J40B3RMn5cPsenl3-1","log.logger":"org.codelibs.fess.helper.DataIndexHelper","error.type":"org.codelibs.fess.ds.atlassian.AtlassianDataStoreException","error.message":"Failed to access org.codelibs.fess.ds.atlassian.api.confluence.content.GetContentsRequest@3e494d","error.stack_trace":"org.codelibs.fess.ds.atlassian.AtlassianDataStoreException: Failed to access org.codelibs.fess.ds.atlassian.api.confluence.content.GetContentsRequest@3e494d\n\tat org.codelibs.fess.ds.atlassian.api.confluence.content.GetContentsRequest.execute(GetContentsRequest.java:92)\n\tat org.codelibs.fess.ds.atlassian.api.confluence.ConfluenceClient.getContents(ConfluenceClient.java:100)\n\tat org.codelibs.fess.ds.atlassian.ConfluenceDataStore.storeData(ConfluenceDataStore.java:72)\n\tat org.codelibs.fess.ds.AbstractDataStore.store(AbstractDataStore.java:122)\n\tat org.codelibs.fess.helper.DataIndexHelper$DataCrawlingThread.process(DataIndexHelper.java:218)\n\tat org.codelibs.fess.helper.DataIndexHelper$DataCrawlingThread.run(DataIndexHelper.java:204)\nCaused by: org.codelibs.fess.ds.atlassian.AtlassianDataStoreException: Failed to access https://pm.betvsys.com:8002/rest/api/latest/content\n\tat org.codelibs.fess.ds.atlassian.api.AtlassianRequest.getCurlResponse(AtlassianRequest.java:118)\n\tat org.codelibs.fess.ds.atlassian.api.AtlassianRequest.getCurlResponse(AtlassianRequest.java:73)\n\tat org.codelibs.fess.ds.atlassian.api.confluence.content.GetContentsRequest.execute(GetContentsRequest.java:86)\n\t... 5 more\nCaused by: org.codelibs.curl.CurlException: Failed to process a request.\n\tat org.codelibs.curl.CurlRequest.lambda$execute$6(CurlRequest.java:271)\n\tat org.codelibs.curl.CurlRequest.lambda$connect$4(CurlRequest.java:233)\n\tat org.codelibs.curl.CurlRequest.connect(CurlRequest.java:243)\n\tat org.codelibs.curl.CurlRequest.execute(CurlRequest.java:270)\n\tat org.codelibs.fess.ds.atlassian.api.AtlassianRequest.getCurlResponse(AtlassianRequest.java:116)\n\t... 7 more\nCaused by: org.codelibs.curl.CurlException: Failed to access to https://pm.betvsys.com:8002/rest/api/latest/content?expand=space%2Cversion%2Cbody.view&start=0&limit=25\n\t... 11 more\nCaused by: org.codelibs.curl.CurlException: Failed to access the response.\n\tat org.codelibs.curl.CurlRequest$RequestProcessor.accept(CurlRequest.java:312)\n\tat org.codelibs.curl.CurlRequest$RequestProcessor.accept(CurlRequest.java:289)\n\tat org.codelibs.curl.CurlRequest.lambda$connect$4(CurlRequest.java:231)\n\t... 10 more\nCaused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching pm.betvsys.com found.\n\tat java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)\n\tat java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)\n\tat java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)\n\tat java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)\n\tat java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)\n\tat java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)\n\tat java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)\n\tat java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)\n\tat java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)\n\tat java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)\n\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)\n\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)\n\tat java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)\n\tat java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)\n\tat org.codelibs.curl.CurlRequest$RequestProcessor.accept(CurlRequest.java:309)\n\t... 12 more\nCaused by: java.security.cert.CertificateException: No subject alternative DNS name matching pm.betvsys.com found.\n\tat java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)\n\tat java.base/sun.security.util.HostnameChecker.match(Unknown Source)\n\tat java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)\n\tat java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)\n\tat java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)\n\tat java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)\n\t... 31 more\n"}

I've check the SSL , and import to the /lib/security/cacerts.
check link:  [How to obtain the location of cacerts of the default java installation?](https://stackoverflow.com/questions/11936685/how-to-obtain-the-location-of-cacerts-of-the-default-java-installation)[https://stackoverflow.com/a/36483016/11882246]

would you help me? thanks

**Comment by marevol** [comment]
For questions about Fess, please use the [Fess Forum](https://discuss.codelibs.org/c/fessen/).
